name: Deploy to IIS

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.0.x

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./Presentation/Nop.Web/Nop.Web.csproj -c Release -o ./publish

      - name: Deploy to IIS
        uses: microsoft/iis-deploy@v1
        with:
          website-name: ${{ secrets.IIS_SITE_NAME }}
          server-computer-name: https://${{ secrets.IIS_SERVER }}:8172/msdeploy.axd
          username: ${{ secrets.DEPLOYER_USERNAME }}
          password: ${{ secrets.DEPLOYER_PASSWORD }}
          package: ./publish